version: '3.5'
service:
  news:
    container_name: 'news'
    build: ./news
    restart: 'on-failure'
    ports:
      - '8080:8080'
    depend_on:
      - elasticsearch
      - postgresql
      - redis
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
    ports:
      - '9200:9200'
  postgresql:
    container_name: 'postgresql'
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=newssecret
      - POSTGRES_USER=newshuser
      - POSTGRES_DB=newsdb
      - POSTGRES_HOST=newshost
  redis:
    container_name: 'redis'
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  db-data: